### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by localhostdotdev** [rails/coffee-rails#113]
The depreciation warning got fixed but it's not in a new version thus users have to pull the gem from github to remove that depreciation warning.

https://github.com/rails/coffee-rails/commit/cbf6af63ac57cea246b75275ba50769d12f43316

**Comment by rafaelfranca** [comment]
We can't release a new version because this gem is broken right now. We need to fix it first. Anyway, this is in our least of things to be done before the release.

**Comment by jasnow** [comment]
@rafaelfranca  - Thanks for the update.

**Comment by rafaelfranca** [comment]
oops, it was not supposed to be closed

**Comment by localhostdotdev** [comment]
just saw `5.0.0` release on April 23, 2019, thx
