### ISSUE TITLE
ExternalInterface from Actionscript not working

### ISSUE THREAD

**Issue by onesneakymofo** [rails/coffee-rails#67]
Hey all,

Just found a bug, and I'm not sure if it's Coffeescript or if it's coffee-rails.  When you're using ExternalInterface in a .swf file to call a Javascript function, the function is being ignored. I had to convert my Coffee file back to Javascript for the .swf to work.

Just a heads up.

**Comment by rafaelfranca** [comment]
coffee-rails is just a integration of coffeescript with Rails. What you described seems to be a coffeescript problem.

**Comment by sikachu** [comment]
I'm pretty sure that's CoffeeScript bug, and that might be because they wrap generated JavaScript result in a closure by default. You can try by redefine your function attaching it to `window` object, and see if that work.

```coffeescript
# Instead of
testing = ->
  alert("Hello!")

# Do this
window.testing = ->
  alert("Hello!")

**Comment by onesneakymofo** [comment]
Thanks @rafaelfranca. That's what I figured. I wanted to check here first just in case. @sikachu, I'll try it and see.
