### ISSUE TITLE
"undefined" compiles improperly?

### ISSUE THREAD

**Issue by nitsujri** [rails/coffee-rails#69]
The simple line:

    if typeof emptyVar != "undefined"
      alert "not empty"

In Rails this gets compiled to:

    if (typeof emptyVar !== void 0){
      return alert "not empty";
    }

`void 0` returns `undefined` while `typeof emptyVar` returns `"undefined"`.

Is this expected behavior?

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is related with CoffeeScript the language, and this project doesn't define the language. Make sure you opened the issue on the correct repository.
