### ISSUE TITLE
How are asset-defined methods called from a view?

### ISSUE THREAD

**Issue by cpg** [rails/coffee-rails#81]
I'm confused on how to call a function `foo` defined in `app/assets/javascripts/foo_file.coffee`. I get `ReferenceError: foo is not defined`

```
foo = (x, y) ->
  alert('this is foo')

#alert('top level alert')
```

from a view that uses `.slim` and coffeescript with:

```
coffee:
  $ ->
    $(document).on "turbolinks:load", ->
      foo('a', '#b')
```

I know the `foo.coffee` is loaded, as I can see the top-level alert commented out in that file.

I have used CS with SLIM in this fashion extensively before and it's great, but always with ajax hooks, etc.. Now I want to move some of the code from pages to a common file in the proper place, but calling it seems to be that I need a little something to make that happen.

Suggestions?

**Comment by prathamesh-sonpatki** [comment]
Please use stackoverflow or other medium for posting questions where a wider community can help you, we reserve the issue tracker for bug reports only, thanks.

**Comment by cpg** [comment]
Should the method be accessible?

If not, would it be a bug, presumably in how coffee-rails does the loading/integration?

**Comment by prathamesh-sonpatki** [comment]
The function is not accessible because it is not bound to window object. 

``` coffee
@foo = (x, y) ->
  alert('this is foo')
```

This will attach the `foo` function to the window object and then can be called outside of this file from anywhere.
