### ISSUE TITLE
Doesn't Register Sprockets Transformer or Mime Type

### ISSUE THREAD

**Issue by tomprats** [rails/coffee-rails#82]
I've been familiarizing myself with Sprockets and how the Transformers and Processors work, but when I was trying to write a Preprocessor for Coffee I noticed I couldn't. I believe this gem handles converting Coffee to JS, but I was wondering why it uses an alternate route.

Is there any way to add preprocessors to it?

**Comment by rafaelfranca** [comment]
Which alternative route are you talking about?

**Comment by tomprats** [comment]
Sorry I'm not very familiar with how this gem works yet, but I was referring to using `register_template_handler` versus the sprockets register methods.

To add some context, I was working on building an alternative to https://github.com/jsdf/sprockets-coffee-react and my work so far is in https://github.com/tomprats/sprockets-cjsx. I had to add a transformer for coffee because I couldn't find a way to hook into this gem in the way a preprocessor would for sprockets.

**Comment by guilleiguaran** [comment]
@tomprats hello, actually this gem doesn't handle converting coffee to js, this is done in sprockets itself in [CoffeeScriptProcessor](https://github.com/rails/sprockets/blob/master/lib/sprockets/coffee_script_processor.rb) using the coffee-script gem that's a wrapper for coffee-script [JS lib](https://www.npmjs.com/package/coffee-script) executed in Ruby thanks to [ExecJS](https://github.com/rails/execjs)

**Comment by guilleiguaran** [comment]
The included template handler and the `register_template_handler` method is for .coffee views living under `app/views` in Rails applications, not for Sprockets processors.

**Comment by tomprats** [comment]
Oh wow, thanks @guilleiguaran. I'll look into that. I misinterpreted the first part of the description "CoffeeScript adapter for the Rails asset pipeline". Thanks for all your help guys!
