### ISSUE TITLE
ReferenceError: CoffeeScript is not defined with coffee-script-source 1.12.1

### ISSUE THREAD

**Issue by thezed** [rails/coffee-rails#84]
<img width="558" alt="2016-12-16 0 30 47" src="https://cloud.githubusercontent.com/assets/1139160/21241273/b0cfa968-c330-11e6-9f02-6b9357feb0df.png">

Switching back to version 1.11.1 solves the issue

**Comment by guilleiguaran** [comment]
coffee-script-source 1.12.1  was yanked

**Comment by thezed** [comment]
But this version still bundles with 'bundle update'

**Comment by guilleiguaran** [comment]
I see, we should wait to get fixed the problem in upstream (https://github.com/jashkenas/coffeescript/issues/4403) before of publishing a new version of the gem

**Comment by guilleiguaran** [comment]
I've released a new version of coffee-script-source https://rubygems.org/gems/coffee-script-source/versions/1.12.2
