### ISSUE TITLE
All Ruby's Tests failed because of NameError: uninitialized constant ActionView::DependencyTracker

### ISSUE THREAD

**Issue by junaruga** [rails/coffee-rails#93]
I would share you that current master branch's tests are failed.
https://travis-ci.org/rails/coffee-rails/branches

Below are latest build for master branch.
https://travis-ci.org/rails/coffee-rails/builds/228967808

For example about Ruby 2.4.0
https://travis-ci.org/rails/coffee-rails/jobs/228967838

```
$ bundle exec rake
...
TemplateHandlerTest#test_coffee_views_are_served_as_javascript:
NameError: uninitialized constant ActionView::DependencyTracker
...
```

**Comment by jasnow** [comment]
Here is a repo affected by same message:
  * https://github.com/jasnow/show-me-the-food5edge

First run "rake" on the repo before updating and see that it runs cleanly.

Then run "bundle update" to get newest edge coffee-rails gem and run "rake" and see the above message.

**Comment by rafaelfranca** [comment]
Fixed
