### ISSUE TITLE
ruby 2.5.1 and rails 5.1.6

### ISSUE THREAD

**Issue by dougharman** [rails/coffee-rails#97]
Just upgraded to ruby 2.5.1 and rails 5.1.6 and I keep getting this error (full trace below): Sun Apr 01 09:44:32 dougharman ~/projects/cpe_tracking$ rails g migration addColumnsToCpeEvents course_location:string course_instructor:string
/Users/dougharman/.rvm/gems/ruby-2.5.1/gems/coffee-rails-4.2.2/lib/coffee-rails.rb:1:in `require': cannot load such file -- coffee-script (LoadError)

The way I resolve it is by following the path and deleting the coffee-rails.rb file  

Since I'm a realtively new developer, I'm not sure if the issue is me or a conflict with the new version of rails.  Hope this report is warranted and doesn't just waste your time.  Thanks, Doug

Here's the full trace:
Sun Apr 01 09:44:32 dougharman ~/projects/cpe_tracking$ rails g migration addColumnsToCpeEvents course_location:string course_instructor:string
/Users/dougharman/.rvm/gems/ruby-2.5.1/gems/coffee-rails-4.2.2/lib/coffee-rails.rb:1:in `require': cannot load such file -- coffee-script (LoadError)
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/coffee-rails-4.2.2/lib/coffee-rails.rb:1:in `<top (required)>'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
	from /Users/dougharman/projects/cpe_tracking/config/application.rb:5:in `<top (required)>'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/dougharman/.rvm/gems/ruby-2.5.1/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/dougharman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/dougharman/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'

**Comment by robin850** [comment]
Hi @dougharman,

Did you re-run `bundle` inside your project once you upgraded to Ruby 2.5.1 ? That looks like a problem with RVM and the way it manages gemsets ; I'm not able to reproduce this locally.

**Comment by robin850** [comment]
@dougharman : No problem ! Thanks for answering back ! :-)
